name: Serverless Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: yarn --network-concurrency 1

      # - name: Run tests
      #   run: |
      #     NODE_ENV=test
      #     yarn test

      - name: Copy env # copy in your env file
        run: 'echo -e "${{secrets.ENV}}" > .env'

      - name: Build
        run: 
